const actionTypes = {
  SELECT_PREPARATION: 'SELECT_PREPARATION',
  SELECT_BEFORE: 'SELECT_BEFORE',
  SELECT_DURING: 'SELECT_DURING',
  SELECT_AFTER: 'SELECT_AFTER',
  ADD_PREPARATION: 'ADD_PREPARATION',
  ADD_BEFORE: 'ADD_BEFORE',
  ADD_DURING: 'ADD_DURING',
  ADD_AFTER: 'ADD_AFTER',
  REMOVE_PREPARATION: 'REMOVE_PREPARATION',
  REMOVE_BEFORE: 'REMOVE_BEFORE',
  REMOVE_DURING: 'REMOVE_DURING',
  REMOVE_AFTER: 'REMOVE_AFTER',
  SET_DISASTER_TYPE: 'SET_DISASTER_TYPE',
};

export default actionTypes;
